Repository codeit-sprint-10/globalNomard, pull requests merged in 2024-02, with the labels that each got.

#16 [이태희] 공용 일반 버튼 컴포넌트 UI 완성
  src/app/test/page.tsx
  src/components/Button/AddButton/AddButton.tsx
  src/components/Button/ArrowButton/ArrowButton.tsx
  src/components/Button/Button.tsx
  src/components/Button/PlainButton/PlainButton.tsx
  src/components/components.txt
Labels: 컴포넌트

#19 [이태희] 공용 버튼: Arrow 버튼 , Add 버튼 추가
  next.config.mjs
  package-lock.json
  package.json
  src/app/test/page.tsx
  src/assets/icons/Arrow_left.svg
  src/assets/icons/Arrow_right.svg
  src/assets/icons/btn_minus.svg
  src/assets/icons/btn_plus.svg
  src/components/Button/AddButton/AddButton.style.ts
  src/components/Button/AddButton/AddButton.tsx
  src/components/Button/ArrowButton/ArrowButton.style.ts
  src/components/Button/ArrowButton/ArrowButton.tsx
  src/components/Button/Button.tsx
  src/components/Button/PlainButton/PlainButton.style.ts
  src/components/Button/PlainButton/PlainButton.tsx
Labels: 컴포넌트

#26 [이태희] 폴더 구조 및 경로 수정
  app/(auth)/_components/input/Input.style.ts
  app/(auth)/_components/input/Input.tsx
  app/(auth)/_components/input/Test.tsx
  app/(auth)/signin/page.tsx
  app/(auth)/signup/page.tsx
  app/(user)/_components/SideMenu/Menu/Menu.style.ts
  app/(user)/_components/SideMenu/Menu/Menu.tsx
  app/(user)/_components/SideMenu/SideMenu.style.ts
  app/(user)/_components/SideMenu/SideMenu.tsx
  app/(user)/test/page.tsx
  app/_api/api.txt
  app/_components/Button/AddButton/AddButton.style.ts
  app/_components/Button/AddButton/AddButton.tsx
  app/_components/Button/ArrowButton/ArrowButton.style.ts
  app/_components/Button/ArrowButton/ArrowButton.tsx
  app/_components/Button/Button.tsx
  app/_components/Button/PlainButton/PlainButton.style.ts
  app/_components/Button/PlainButton/PlainButton.tsx
  app/_components/Profile/Profile.style.ts
  app/_components/Profile/Profile.tsx
  app/_hooks/usehooks.txt
  app/_lib/registry.tsx
  app/_styles/GlobalStyles.ts
  app/_styles/sign.style.ts
  app/assets/icons/Arrow_left.svg
  app/assets/icons/Arrow_right.svg
  app/assets/icons/ExperienceManagement.svg
  app/assets/icons/Pen.svg
  app/assets/icons/ReservationDetails.svg
  app/assets/icons/btn_minus.svg
  app/assets/icons/btn_plus.svg
  app/assets/icons/currentSituation.svg
  app/assets/icons/info.svg
  app/layout.tsx
  app/page.tsx
  package-lock.json
  public/fonts/font.txt
  public/images/index.ts
  public/images/testImg.jpg
  public/next.svg
  public/vercel.svg
  tsconfig.json
  yarn.lock
Labels: Fix, 세팅

#29 Feat: Footer, GNB
  app/(auth)/layout.tsx
  app/(user)/_components/Footer/Footer.tsx
  app/(user)/_components/Footer/footer.style.ts
  app/(user)/_components/GNBMenuButton/GNBMenuButton.tsx
  app/(user)/_components/GNBMenuButton/gnbMenuButton.style.ts
  app/(user)/_components/GNBNav/GNBNav.tsx
  app/(user)/_components/GNBNav/gnbNav.style.ts
  app/(user)/_components/LogoButton/LogoButton.tsx
  app/(user)/_components/LogoButton/logoButton.style.tsx
  app/(user)/_components/ProfileButton/ProfileButton.tsx
  app/(user)/_components/ProfileButton/profileButton.style.ts
  app/(user)/layout.tsx
  app/(user)/my/memberinfo/page.tsx
  app/_components/Button/Button.tsx
  app/_styles/Text.style.tsx
  app/_types/user.types.ts
  app/assets/icons/FacebookIcon.tsx
  app/assets/icons/InstagramIcon.tsx
  app/assets/icons/TwitterIcon.tsx
  app/assets/icons/YoutubeIcon.tsx
  app/assets/icons/icons_facebook.svg
  app/assets/icons/icons_instagram.svg
  app/assets/icons/icons_twitter.svg
  app/assets/icons/icons_youtube.svg
  app/layout.tsx
  app/page.tsx
  package-lock.json
  public/images/logo.png
  public/images/logo_small.png
  public/images/profile_mini.png
  yarn.lock
Labels: 컴포넌트

#36 Feat: api 일부
  app/(auth)/signin/page.tsx
  app/(auth)/signup/page.tsx
  app/(user)/_components/GNBMenuButton/GNBMenuButton.tsx
  app/(user)/_components/GNBNav/GNBNav.tsx
  app/_api/api.ts
  app/_api/api.txt
  app/_api/postNewUser.ts
  app/_api/postUser.ts
  app/_api/type.ts
  app/_hooks/useSignin.tsx
  app/_hooks/useSignup.tsx
  app/_hooks/useUserinfo.ts
  app/_hooks/usehooks.txt
  package-lock.json
  package.json
  yarn.lock
Labels: API

#55 ReservationCard 썸네일 수정
  app/(user)/_components/reservationCard/ReservationCard.tsx
Labels: Fix

#58 GNBNav api
  app/(user)/_components/GNBNav/GNBNav.tsx
  app/(user)/_components/ProfileButton/ProfileButton.tsx
  app/_api/postUser.ts
  app/page.tsx
Labels: Fix
